# Generated by Django 4.2.7 on 2025-06-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Информация'), ('news', 'Новости'), ('alert', 'Оповещение')], default='info', max_length=50, verbose_name='Тип контента')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок (рус)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Заголовок (каз)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (англ)')),
                ('text', models.TextField(verbose_name='Текст (рус)')),
                ('text_kz', models.TextField(verbose_name='Текст (каз)')),
                ('text_en', models.TextField(verbose_name='Текст (англ)')),
                ('time', models.DateTimeField(verbose_name='Время отправки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['time'], name='botapp_cont_time_73a9df_idx')],
            },
        ),
    ]
