# Generated by Django 4.2.7 on 2025-06-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-time'], 'permissions': [('can_publish', 'Может публиковать контент')], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AddField(
            model_name='content',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
        migrations.AddField(
            model_name='content',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('info', 'Информация'), ('news', 'Новости'), ('alert', 'Оповещение'), ('event', 'Событие'), ('promo', 'Акция')], default='info', max_length=50, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['is_published'], name='botapp_cont_is_publ_608036_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['type', 'is_published'], name='botapp_cont_type_85cced_idx'),
        ),
    ]
