# Generated by Django 4.2.7 on 2025-06-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_alter_content_options_content_is_pinned_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
