# Generated by Django 4.2.7 on 2025-06-14 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botapp', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kz', 'Қазақша'), ('en', 'English')], default='ru', max_length=10)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки бота пользователя',
                'verbose_name_plural': 'Настройки бота пользователей',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
