# Generated by Django 4.2.7 on 2025-06-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_userbotsettings_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField(unique=True)),
                ('content_type', models.CharField(choices=[('info', 'Информация'), ('news', 'Новость'), ('promo', 'Акция')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('title_kz', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('text_kz', models.TextField()),
                ('text_en', models.TextField()),
                ('send_time', models.DateTimeField()),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ['-send_time'],
            },
        ),
        migrations.DeleteModel(
            name='UserBotSettings',
        ),
    ]
