# Generated by Django 4.2.7 on 2025-06-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_content_delete_userbotsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image_path',
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='content_images/', verbose_name='Изображение'),
        ),
    ]
