# Generated by Django 4.2.7 on 2025-06-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0008_userbotsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('info', 'Информация'), ('news', 'Новость'), ('ask', 'ask')], max_length=10),
        ),
    ]
