# Generated by Django 4.2.7 on 2025-06-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0010_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbotsettings',
            name='user',
            field=models.BigIntegerField(unique=True),
        ),
    ]
