# Generated by Django 4.2.7 on 2025-06-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0011_alter_userbotsettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbotsettings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
