# Generated by Django 4.2.7 on 2025-06-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0012_alter_userbotsettings_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbotsettings',
            old_name='user',
            new_name='telegram_id',
        ),
    ]
