# Generated by Django 4.2.7 on 2026-06-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0014_userbotsettings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_kz', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Сессия на выбор',
                'verbose_name_plural': 'Сессия на выбор',
            },
        ),
    ]
