# Generated by Django 4.2.7 on 2026-06-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0015_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='selected_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='botapp.sessions'),
        ),
        migrations.AddField(
            model_name='userbotsettings',
            name='selected_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_settings', to='botapp.sessions'),
        ),
    ]
