# Generated by Django 4.2.7 on 2026-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0016_content_selected_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_session_select_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='selected_sessions',
            field=models.ManyToManyField(blank=True, related_name='contents_for_choise', to='botapp.sessions'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('info', 'Информация'), ('news', 'Новость'), ('ask', 'ask')], max_length=25),
        ),
    ]
